name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: checking composer
      run: composer --version
    
    - name: installing composer dependencies
      run: composer install
    - name: running unit test on the package
      run: ./vendor/bin/phpunit
